### ISSUE TITLE
Use ref

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-text-input#1]
Is it possible to use ref with this component?
I want to autofocus the input on showing up

**Comment by kuraydev** [comment]
I made it strict but it can doable, I will do it :)

**Comment by mariomurrent-softwaresolutions** [comment]
Awesome thx

**Comment by kuraydev** [comment]
Hello again @mariomurrent-softwaresolutions 

Here is the `inputRef` prop with the [New Release 0.1.2  🥳](https://github.com/WrathChaos/react-native-text-input/releases/tag/0.1.2)

**Comment by mariomurrent-softwaresolutions** [comment]
Awesome thx - I'll try it out tomorrow 😎😎🎊🤩
