### ISSUE TITLE
onPress not working

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-text-input#2]
I'm using the text input with the button in a modal dialog with and without an own ImageComponent.

But somehow the onPress is not triggered. Seems like sometimes it works, but most of the time not.

` <RNTextInput
                    style={styles.inputStyle}
                    textInputStyle={styles.textInput}
                    onChangeText={this.handleAdditionalDataDescriptionChange}
                    onPress={this.handlePress}
                />`

**Comment by kuraydev** [comment]
Hello @mariomurrent-softwaresolutions,
I tried to reproduce it but it works on my side. Can you share a reproducible example with me? Then I can investigate and fix the bug.

**Comment by mariomurrent-softwaresolutions** [comment]
Sure I will try

**Comment by kuraydev** [comment]
@mariomurrent-softwaresolutions I believe that [0.1.2 version](https://github.com/WrathChaos/react-native-text-input/releases/tag/0.1.2) can fix this problem, can you try it?

**Comment by mariomurrent-softwaresolutions** [comment]
Sure, I'll let you know tomorrow 😊
And thx for the fast response

**Comment by mariomurrent-softwaresolutions** [comment]
Seems to be working now :) If I detect some issue I will reopen this one
