### ISSUE TITLE
Placeholder is not updated

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-text-input#3]
If placeholder value is taken from e.g state the value is not updates. 
It will always be the first value

**Comment by mariomurrent-softwaresolutions** [comment]
PR for that is open :)

**Comment by kuraydev** [comment]
Here we go :) 

Thank you so much @mariomurrent-softwaresolutions  

## [Release 0.1.3 🥳](https://github.com/WrathChaos/react-native-text-input/releases/tag/0.1.3)

**Comment by mariomurrent-softwaresolutions** [comment]
Thx 😉
