### ISSUE TITLE
Hitting the outside of the text field does not focus the text

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-text-input#5]
Please have a look at the following video: https://meecode.at/customers/git/RPReplay_Final1617277639.mov

When I hit the outside of the textbox it does not focus the inside. Is this a norma behaviour?

**Comment by kuraydev** [comment]
It does not have autofocus right now, you can simply make it possible with the ref and inputRef?.focus() function.

**Comment by mariomurrent-softwaresolutions** [comment]
I did not mean the autofocus, but it seems that pressing on the outside (the bouncable) does not focus the text field

**Comment by kuraydev** [comment]
Yes the library does not handle the focus when there is a pressing on the outside because dev can handle it with `onPress`. If I misunderstood something, please explain it to me :)

**Comment by mariomurrent-softwaresolutions** [comment]
Okay I'll try to figure that out 😊
Thx

**Comment by kuraydev** [comment]
`inputRef?.focus()` should resolve this issue :) @mariomurrent-softwaresolutions

**Comment by mariomurrent-softwaresolutions** [comment]
Works like a charm. Thx - I really didn't see that option ...
