### ISSUE TITLE
disableButton is not working anymore

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [WrathChaos/react-native-text-input#6]
I set the disableButton attribute for the input, but the button is display regardless of the value set.

Version 1.0.3 works fine

**Comment by kuraydev** [comment]
Thank you for reporting this @mariomurrent-softwaresolutions 

[Release 0.1.8](https://github.com/WrathChaos/react-native-text-input/releases/tag/0.1.8) is fixing this issue :) Totally my bad. 

Can you please test it out?

Also, waiting for your mail :)

**Comment by mariomurrent-softwaresolutions** [comment]
Thx for the fast update - it is working now :) ..

Oh, I sent a mail to you a few weeks ago - I will recheck it, and answer. Sorry my bad if the mail was not delivered.
